services:
  # Nginx Proxy Manager
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: meteo-proxy
    restart: always
    ports:
      - '${NPM_HTTP_PORT}:80'
      - '${NPM_HTTPS_PORT}:443'
      - '${NPM_ADMIN_PORT}:81'
    volumes:
      - ./npm-data:/data
      - ./npm-letsencrypt:/etc/letsencrypt

  # Base de Datos
  mongodb:
    image: mongo:latest
    container_name: meteo-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - ./meteo-data:/data/db

  # Servidor API
  api:
    build: ./api
    container_name: meteo-api
    restart: always
    environment:
      # Pasamos la URL de conexi√≥n construida con las variables del .env
      - MONGO_URL=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongodb:27017/${MONGO_DB_NAME}?authSource=admin
      - PORT=${API_PORT}
    depends_on:
      - mongodb

volumes:
  meteo-data:
